print('hello world\nlineB')
print('this is \\\\ double backslash')
print('these are /\\/\\/\\/\\ mountains')
print('\\" \\n \\t \\\'')
print(r"lo\nhoo")
print("\U0001F47B")
print(2**0.5)
print(round(2**0.5,4))
print(2**3/2*6-4)