# Generated by Django 3.2.5 on 2021-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
