CC = gcc
CPP = g++
FLAGS = -o

Binarytree:
	$(CC) $(FLAGS) Binarytree.out Binarytree.c
	echo "✅ Compiled"

Sorting:
	$(CPP) $(FLAGS) Sorting.out Sorting.cpp
	echo "✅ Compiled"

Linklist:
	$(CPP) $(FLAGS) Linklist.out Linklist.cpp
	echo "✅ Compiled"

Stack:
	$(CC) $(FLAGS) Stack.out Stack.c
	echo "✅ Compiled"

clean:
	rm *.out
	echo "🧹 Cleaned"